---

- name: packages
  apt: >
    name={{ item }}
    state=present
  with_items:
    - gearman-server
  sudo: yes

- name: service
  service: >
    name=gearman-server
    state=started
    enabled=yes
  sudo: yes
